KerasJson: ../../../example-models/keras/KERAS_1layer.json
KerasH5:   ../../../example-models/keras/KERAS_1layer_weights.h5
InputData: ../../../example-models/keras/KERAS_1layer_input_features.dat
OutputPredictions: ../../../example-models/keras/KERAS_1layer_predictions.dat
OutputDir: keras_1layer
ProjectName: keras1layer
XilinxPart: xcku115-flvb2104-2-i
ClockPeriod: 5

IOType: io_parallel # options: io_serial/io_parallel
HLSConfig:
  Model:
    Precision: ap_fixed<18,8>
    ReuseFactor: 1
    Strategy: Resource
#  LayerType:
#    Dense:
#      ReuseFactor: 2
#      Strategy: Resource
#      Compression: True
